.TH "MKWIN" "1" "March 2021" "0.1" ""
.hy
.SH NAME
.PP
mkwin \[en] Windows installation media creator
.SH SYNOPSIS
.PP
\f[B]mkwin\f[] <\f[I]iso\f[]> [\f[I]device\f[]] [\f[I]label\f[]]
.SH DESCRIPTION
.PP
mkwin is a shell script to create a Windows installation USB from an
ISO.
It support EFI and legacy boot for Windows 7 and up.
.SH GENERAL OPTIONS
.TP
.B \f[I]iso\f[]
ISO file of installation media
.RS
.RE
.TP
.B \f[I]device\f[]
Device path for target USB drive
.RS
.PP
Dialog asks for device if not specified
.RE
.TP
.B \f[I]label\f[]
Label to put on NTFS partition
.RS
.PP
Defaults to "\f[B]WindowsInstaller\f[]"
.RE
.SH AUTHORS
Lily Foster <lily@lily.flowers>.
